version: '3'

services:
  base-datos:
    image: postgres
    container_name: api
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api-rest
  api:
    build: .
    
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - base-datos