# Generated by Django 5.0.4 on 2024-05-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='client',
        ),
    ]
